# Generated by Django 5.1.5 on 2025-02-13 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_activeorders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveOrders',
        ),
    ]
