# Generated by Django 5.1.5 on 2025-02-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeorders',
            name='active',
        ),
        migrations.AddField(
            model_name='activeorders',
            name='status',
            field=models.CharField(choices=[('preparing', 'Preparing'), ('delivering', 'Delivering'), ('delivered', 'Delivered')], default='preparing', max_length=20),
        ),
    ]
