# Generated by Django 5.1.5 on 2025-02-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatit', '0002_remove_activeorders_active_activeorders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeorders',
            name='status',
        ),
        migrations.AddField(
            model_name='activeorders',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
